# Generated by Django 5.2.11 on 2026-02-06 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_red', models.CharField(default='Player 1 (Red)', max_length=100)),
                ('player_green', models.CharField(default='Player 2 (Green)', max_length=100)),
                ('current_turn', models.IntegerField(default=1)),
                ('width', models.IntegerField(default=10)),
                ('height', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('order', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='game.game')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('game', 'x', 'y')},
            },
        ),
    ]
